### ISSUE TITLE
feat: Triplet Sum of Arrays

### ISSUE THREAD

**Issue by khushis28** [Im-Soumya/Hacktoberfest_2023#115]
The purpose of the program is to find and print all unique combinations of three elements from the arr vector that sum up to a specific target value (sum), which is set to 80. 

This program utilizes nested loops to generate these combinations.

**Comment by khushis28** [comment]
this PR has been excluded from Hacktoberfest 2023, just got to know after merging my PR

**Comment by Im-Soumya** [comment]
Sorry for the inconvenience, I should have checked this earlier, I'll look
into this issue.
